steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_API_BASE=${_API_BASE}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}
      - -t
      - us-central1-docker.pkg.dev/${PROJECT_ID}/sprout/frontend:${_IMAGE_TAG}
      - -t
      - us-central1-docker.pkg.dev/${PROJECT_ID}/sprout/frontend:latest
      - .
images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/sprout/frontend:${_IMAGE_TAG}
  - us-central1-docker.pkg.dev/${PROJECT_ID}/sprout/frontend:latest
substitutions:
  _API_BASE: https://api.sprout.asad.codes
  _FIREBASE_API_KEY: ""
  _FIREBASE_AUTH_DOMAIN: ""
  _FIREBASE_PROJECT_ID: ""
  _FIREBASE_APP_ID: ""
  _IMAGE_TAG: latest
